- hosts: servers
  become: true
  tasks:

  - name: update apt cache
    apt:
      update_cache=true

  - name: apt packages are installed
    apt: name={{ item }}
    with_items:
      - python3-pip
      - python3-virtualenv
      - git
      - acl

  - name: user exists
    user:
      name={{ unix_user }}
      state=present
      shell=/bin/bash

  - name: deployment directory exists
    file:
      state=directory
      path={{ deployment_path }}
      owner={{ unix_user }}
      group={{ unix_user }}

  - name: cloned repo
    become_user: '{{ unix_user }}'
    git:
      dest={{ deployment_path }}
      repo={{ repo }}
      version=master
      accept_hostkey=true

  - name: python modules are installed
    become_user: '{{ unix_user }}'
    pip:
      requirements={{ deployment_path }}/requirements.txt
      virtualenv={{ virtualenv }}

  - name: models are migrated
    become_user: '{{ unix_user }}'
    django_manage:
      app_path={{ deployment_path }}
      virtualenv={{ virtualenv }}
      command=migrate

  - name: ensure static files are collected
    become_user: '{{ unix_user }}'
    django_manage:
        app_path={{ deployment_path }}
        virtualenv={{ virtualenv }}
        command=collectstatic

  - name: nginx is installed
    apt: name=nginx

  - name: nginx log directory exists
    file:
      state=directory
      path=/var/log/nginx/{{ project_name }}
      owner=www-data

  - name: nginx configuration in sites-available
    template: >
        dest=/etc/nginx/sites-available/{{ nginx_conf }}
        src=nginx.conf
    notify:
    - reload nginx

  - name: nginx conf is symlinked to sites-enabled
    file: >
        src=/etc/nginx/sites-available/{{ nginx_conf }}
        path=/etc/nginx/sites-enabled/{{ nginx_conf }}
        state=link

  - name: reload ready nginx
    service:
      name=nginx
      state=reloaded

  - name: uwsgi and plugins installed
    apt: name={{ item }}
    with_items:
    - uwsgi
    - uwsgi-plugin-python3

  - name: uwsgi configured
    lineinfile:
      dest=/etc/default/uwsgi
      line='export LANG=en_US.UTF-8'
      insertafter=EOF

  - name: uwsgi conf in apps-available
    template:
      dest=/etc/uwsgi/apps-available/{{ project_name }}.ini
      src=uwsgi.ini

  - name: uwsgi conf symlinked to apps-enabled
    file:
      src=/etc/uwsgi/apps-available/{{ project_name }}.ini
      path=/etc/uwsgi/apps-enabled/{{ project_name }}.ini
      state=link

  - name: uwsgi restarted
    service:
      name=uwsgi
      state=restarted

  - name: services are running
    service:
      name={{ item.name }}
      state=restarted
      enabled=true
      arguements={{ item.arguments|default(omit) }}
    with_items:
    - name: nginx
    - name: uwsgi
      arguements: '{{ project_name }}'

  handlers:
    - name: reload nginx
      service:
        name=nginx
        state=reloaded
